name = "imps-api-dev"
main = "src/server.ts"
minify = true
compatibility_date = "2022-08-20"
route = "dev.api.imps.com.br/*"

[vars]
JWT_SECRET_KEY = "secret"
FAUNADB_API = "https://graphql.us.fauna.com/graphql"
FAUNADB_SECRET = ""

[env.staging]
name = "imps-api-staging"
route = "staging.imps.com.br/*"

[env.production]
name = "imps-api"
routes = [
  "api.imps.com.br/*"
]
